### ISSUE TITLE
BIOS settings

### ISSUE THREAD

**Issue by ho1yspirt** [adam-ht/Lentosh#1]
Can you provide BIOS settings, just for to be sure.

**Comment by adam-ht** [comment]
| Setting | Value |
|--------|-------|
| UMA Frame buffer Size | 2G |
| AMD SVM Technology | True |
| Above 4 GB MMIO | Disabled |
| Boot Mode | UEFI |

To access advanced bios settings, press from f1 to z from f2 to x from f3 to c from f4 to v from f5 to b from f6 to n

**Comment by ho1yspirt** [comment]
Thanks for the answer! I did exact thing, but under some circumstances like opening firefox macos just reboots with unexpected error after. The only things that i did - deleted WhateverGreen and generated smbios. The laptop is s340 with 14''
